### ISSUE TITLE
How do I install on my server?

### ISSUE THREAD

**Issue by ghost** [VicenteRD/PomodoroBot#4]
Hello. Could you help in guiding with a tutorial how to install this?

**Comment by Trimardio** [comment]
- Create a discord bot https://www.digitaltrends.com/gaming/how-to-make-a-discord-bot/
- Get the bot ID put it in the bot.yml file
- Add it to your server. And get him a role in which he can do almost everything. 
- Get the role ID put it in the bot.yml file
- Modify the bot.yml file and add the appropriate channels
- Go to the bot app and find the TOKEN in bot --> buit-a-bot
- start the server with python3 main.py TOKEN

Not sure why I needed python3, can't remember if I struggle with the dependencies

**Comment by VicenteRD** [comment]
Thanks for helping out, I never saw this :x

@ricardo-7 if you're still having issues, let me know!
